### ISSUE TITLE
Query select() issue when using distance column

### ISSUE THREAD

**Issue by leabdalla** [malhal/Laravel-Geographical#10]
I need only these fields in my query:

    $places->select(
        'id',
        'title',
        'subtitle',
        'distance'
    );

This is working fine so far, but breaks when I add `distance` columns

    $places->distance($params->latitude, $params->longitude);
    $places->orderBy('distance', 'ASC');
    $places->having('distance', '<=', $params->distance);

Adding this code it looks like my previous `select()` is ignored cause it returns all Model fields.

So I tried to put `select()` after `distance` and then it returns column error:

    Column not found: 1054 Unknown column 'distance' in 'field list'

Am I doing something wrong?

**Comment by ashnehete** [comment]
The underlying problem of this issue is that the distance method overrides the select() function of the model. I'm working on trying on a work around.

**Comment by ashnehete** [comment]
I have opened a pull request that will be able to do exactly what you want. Few points though:
1. `select()` should always be called before `distance()/geofence()`.
2. Don't include `distance` in the select column.

**Comment by malhal** [comment]
When I first coded this selectRaw didn’t override any previous selects, see:
https://github.com/laravel/framework/issues/8160
Does selectRaw now clear previous selects?

**Comment by ashnehete** [comment]
The selectRaw doesn't override, thats correct.
But this line did that:
https://github.com/malhal/Laravel-Geographical/blob/c8818b029c291f7d6d0a25f7b701e89ace4a0d71/src/Geographical.php#L25

**Comment by malhal** [comment]
Hmm wonder why it has that...how about just addSelect the lat and lon columns?

**Comment by ashnehete** [comment]
According to the original issue, the author required arbitrary columns. So I felt best way was to give user the optional control to select any columns they need using original Laravel `select()`. Which I think makes it intutive for all users.

Edit: To answer you question, I think that line was there so that by default all the columns are selected. In the absence of that line only, the distance would have been selected.

**Comment by waqas306** [comment]
I have managed to select some required columns by just commenting the line
// $query->select($this->getTable() . '.*');
in scopeDistance function inside Geographical trait.



 public function scopeDistance($query, $latitude, $longitude)
    {
        $latName = $this->getQualifiedLatitudeColumn();
        $lonName = $this->getQualifiedLongitudeColumn();
        // $query->select($this->getTable() . '.*');
