### ISSUE TITLE
Support Laravel 6

### ISSUE THREAD

**Issue by checkerschaf** [malhal/Laravel-Geographical#18]
Hey,

as Laravel 6 has been released, the current composer.json doesn't allow to upgrade to laravel ^6.0.
Do you know if there are any breaking changes in here?

**Comment by malhal** [comment]
I don't know sorry

**Comment by Zubeek91** [comment]
Is there a plan to update this to v6 or is this no longer being maintained ?

**Comment by Grayda** [comment]
I've forked and updated this package here: https://github.com/Auroras-live/Laravel-Geographical/

I haven't tested it yet (I'm in the process of updating to Laravel 6 now), but give it a shot. I can do a PR back if it works fine. From the looks of things, there's no incompatible code in there, so it should just need composer.json updated.

To use my updated repo, just add 

```json
      {
        "url": "https://github.com/Auroras-live/Laravel-Geographical.git",
        "type": "git"
      }
```

To the `repositories` section of your composer.json file, then `composer update`

**Comment by malhal** [comment]
Yes please do a PR and I’ll merge it in
