### ISSUE TITLE
When will you release the new commits?

### ISSUE THREAD

**Issue by anish-techpro** [malhal/Laravel-Geographical#22]
It would be great if you could release the new commits because I need the table prefix update.

Please look into the matter.

**Comment by malhal** [comment]
Hi I just merged the pull request is that what you meant?

**Comment by huynhphan89** [comment]
@malhal please bump a new version. v1.0.1 is too old.

**Comment by anish-techpro** [comment]
> Hi I just merged the pull request is that what you meant?

I meant there is no new release after the merge. Hence, I am not getting the changes if I update. 

As @huynhphan89 mentioned, you need to bump up the version after the merges.

**Comment by malhal** [comment]
Ok there is a 1.0.2 release now

**Comment by anish-techpro** [comment]
> Ok there is a 1.0.2 release now

The package version at https://packagist.org/packages/malhal/laravel-geographical is still at 1.0.1.

Please update that as well.

**Comment by malhal** [comment]
Ok I updated that too.

**Comment by anish-techpro** [comment]
Ok, it has been updated and working. Thanks
