### ISSUE TITLE
Method Illuminate\Database\Eloquent\Collection::distance does not exist.

### ISSUE THREAD

**Issue by Shi974** [malhal/Laravel-Geographical#26]
Hey there.
Great package you made there, I want to say thank you.

I have an issue when using Eloquent query.
For instance, I only want to use distance() for some ids and not the whole Model.
I use :
`$events = Nosevenement::find($ids) -> distance($latitude, $longitude) -> orderBy('distance', 'ASC');`
And i get an error : **Method Illuminate\Database\Eloquent\Collection::distance does not exist.**

I guess we can't combine both for now.
It's a shame because the package is doing wonders so far.

**Comment by malhal** [comment]
The error explains the problem, find() returns a Collection. Collection doesn't have a method distance. Call distance on a query instead.

**Comment by Shi974** [comment]
My bad !
A little tweak did the trick.

`$events = Nosevenement::distance($latitude, $longitude) -> orderBy('distance', 'ASC') -> whereIn('idNosEvenements', $ids) -> get();`

Thanks for the feedback and the package !
