### ISSUE TITLE
 does not install on laravel 5.4

### ISSUE THREAD

**Issue by gutdeveloper** [malhal/Laravel-Geographical#3]
$ composer require malhal/laravel-geographical
Using version ^1.0 for malhal/laravel-geographical
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for malhal/laravel-geographical ^1.0 -> satisfiable by malhal/laravel-geographical[1.0.0].
    - malhal/laravel-geographical 1.0.0 requires laravel/framework 5.3.* -> satisfiable by laravel/framework[5.3.x-dev, v5.3.0, v5.3.0-RC1, v5.3.1, v5.3.10, v5.3.11, v5.3.12, v5.3.13, v5.3.14, v5.3.15, v5.3.16, v5.3.17, v5.3.18, v5.3.19, v5.3.2, v5.3.20, v5.3.21, v5.3.22, v5.3.23, v5.3.24, v5.3.25, v5.3.26, v5.3.27, v5.3.28, v5.3.29, v5.3.3, v5.3.30, v5.3.31, v5.3.4, v5.3.5, v5.3.6, v5.3.7, v5.3.8, v5.3.9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by xitude** [comment]
@malhal do you plan on updating the requires?

**Comment by malhal** [comment]
If you'd like to fix I'd accept the pull request thanks.

**Comment by malhal** [comment]
I merged the change and created a new release 1.0.1. Just checked [packigist](https://packagist.org/packages/malhal/laravel-geographical#1.0.1) and it already got the update

**Comment by xitude** [comment]
Works correctly.

**Comment by malhal** [comment]
Great thanks
