### ISSUE TITLE
Geofence Return Null even the lng and lat are the same.

### ISSUE THREAD

**Issue by jackwander** [malhal/Laravel-Geographical#30]
**Laravel Version**: 7.22

$lat = 122.9563;
$lng = 10.684; 
$in_radius = 30; // What is the measurement of radius?
$out_radius = 30; // What is the measurement of radius?
 
Model::geofence($lat,$lng,$in_radius,$out_radius)->get();

When i use the distance the return value is 0.4412770539854747 but when i use the geofence it return null.

**Comment by C-Spydo** [comment]
Hi @jackwander , how did you later fix this issue? I'm experiencing the same thing

**Comment by jackwander** [comment]
@C-Spydo the in_radius is the starting distance then $out_radius is the max radius.
```Model::geofence($lat,$lng,0,30)->get();```
