### ISSUE TITLE
Publish commit with laravel 9 support on composer packages 

### ISSUE THREAD

**Issue by medeiroz** [malhal/Laravel-Geographical#36]
Publish commit with laravel 9 support on composer packages

**Comment by bluec** [comment]
Yes the change made for Laravel 9.x hasn't been tagged as a release. For the timebeing you can pull in the master branch as follows:

```
composer require malhal/laravel-geographical:dev-master
```

**Comment by malhal** [comment]
Sorry looks like I forgot to do that, I just published a 1.0.5 release
