### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by TartanLeGrand** [malhal/Laravel-Geographical#40]
Support Laravel 11 ?

**Comment by malhal** [comment]
Not sure sorry

**Comment by malhal** [comment]
Please try 1.0.7

**Comment by TartanLeGrand** [comment]
Not publish on https://packagist.org/packages/malhal/laravel-geographical 😄

**Comment by malhal** [comment]
Sorry about that, thought it would auto-update but seems not so I've just done manual update.
