### ISSUE TITLE
Returning Empty Array

### ISSUE THREAD

**Issue by keithgulbro** [malhal/Laravel-Geographical#6]
Hi there,

I am attempting to use the package you created to return results within a particular radius. Per the brief documentation outlined, this is my code:

```
      $latitude = 45.68616989612867;
      $longitude = -87.59278603624216;
      $inner_radius = 1;
      $outer_radius = 1000000000;

      return FFL::geofence($latitude, $longitude, $inner_radius, $outer_radius)->get();
```

The result I receive is an empty array. I updated my model to `use Geographical` and my migration has these two column: 

```
            $table->double('latitude');
            $table->double('longitude');
```

Any ideas you have would be helpful. Regards.

**Comment by malhal** [comment]
Try doing a distance query and examine the values? If you look at the geofence code you'll see its just a between query.
