### ISSUE TITLE
Distance is incorrect?

### ISSUE THREAD

**Issue by jake5253** [malhal/Laravel-Geographical#8]
Using `$query = User::geofence($myLatitude, $myLongitude, 0, 1000)->get()` results that I am 5.8987221219523E-5 away from myself.  Shouldn't it be 0 since I'm passing the exact lat/long it's comparing to?

**Comment by jake5253** [comment]
While I realize this is only a few feet at best,

**Comment by ashnehete** [comment]
If you are interested in knowing the cause, its because of the Haversine formula that is being employed to calulcate the great-circle distance. This formula is not exactly 100% accurate partially due to Earth's ellipitical shape.
